theme: jekyll-theme-cayman
markdown: kramdown
title: Beautiful & Productive Suburban Foodscaping
safe: true
incremental: false
github:
  is_project_page: false
#lsi: false
#source: [your repo's top level directory]
#highlighter: rouge
#gist:
#  noscript: false
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge
#defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#    values:
#      layout: "default"

